export const postDatas = [
  {
    id: 1,
    title: "First Post!",
    img: "https://www.searchenginejournal.com/wp-content/uploads/2020/08/7-ways-a-blog-can-help-your-business-right-now-5f3c06b9eb24e-1520x800.webp",
    postTitle: "Top 10 ways to make a blog",
    link: "https://www.bing.com/",
  },
  {
    id: 2,
    title: "Second Post!",
    img: "https://images.pexels.com/photos/39284/macbook-apple-imac-computer-39284.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    postTitle: "Top 10 ways to make a website",
    link: "https://www.google.com/",
  },
  {
    id: 3,
    title: "First Post!",
    img: "https://www.searchenginejournal.com/wp-content/uploads/2020/08/7-ways-a-blog-can-help-your-business-right-now-5f3c06b9eb24e-1520x800.webp",
    postTitle: "Top 10 ways to make a blog",
    link: "https://www.bing.com/",
  },
  {
    id: 4,
    title: "Second Post!",
    img: "https://images.pexels.com/photos/39284/macbook-apple-imac-computer-39284.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    postTitle: "Top 10 ways to make a website",
    link: "https://www.google.com/",
  },
  {
    id: 5,
    title: "First Post!",
    img: "https://www.searchenginejournal.com/wp-content/uploads/2020/08/7-ways-a-blog-can-help-your-business-right-now-5f3c06b9eb24e-1520x800.webp",
    postTitle: "Top 10 ways to make a blog",
    link: "https://www.bing.com/",
  },
  {
    id: 6,
    title: "Second Post!",
    img: "https://images.pexels.com/photos/39284/macbook-apple-imac-computer-39284.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    postTitle: "Top 10 ways to make a website",
    link: "https://www.google.com/",
  },
  {
    id: 7,
    title: "First Post!",
    img: "https://www.searchenginejournal.com/wp-content/uploads/2020/08/7-ways-a-blog-can-help-your-business-right-now-5f3c06b9eb24e-1520x800.webp",
    postTitle: "Top 10 ways to make a blog",
    link: "https://www.bing.com/",
  },
  {
    id: 8,
    title: "Second Post!",
    img: "https://images.pexels.com/photos/39284/macbook-apple-imac-computer-39284.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    postTitle: "Top 10 ways to make a website",
    link: "https://www.google.com/",
  },
  {
    id: 9,
    title: "First Post!",
    img: "https://www.searchenginejournal.com/wp-content/uploads/2020/08/7-ways-a-blog-can-help-your-business-right-now-5f3c06b9eb24e-1520x800.webp",
    postTitle: "Top 10 ways to make a blog",
    link: "https://www.bing.com/",
  },
  {
    id: 10,
    title: "Second Post!",
    img: "https://images.pexels.com/photos/39284/macbook-apple-imac-computer-39284.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    postTitle: "Top 10 ways to make a website",
    link: "https://www.google.com/",
  },
];
